#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service single
SERVICE_NAME="nginx"

if var_false "${ENABLE_NGINX}" || { [ -f /var/run/s6/basedir/env/ENABLE_NGINX ] && [ "$(cat /var/run/s6/basedir/env/ENABLE_NGINX)" = "FALSE" ]; }; then
    print_debug "Disabling Nginx"
    service_stop 10-nginx
    service_stop 11-nginx-config-reload
    rm -rf \
           /container/logrotate/nginx* \
           /etc/fluent-bit/conf.d/nginx* \
           /etc/logrotate.d/nginx* \
           /etc/zabbix/*/nginx*
    liftoff
    exit 0
fi

if check_container_restarted ; then
    call nginx_server_configure
    if var_true "${NGINX_ENABLE_APPLICATION_CONFIGURATION}"; then
        if [ -z "${NGINX_SITE_ENABLED}" ] || [ "${NGINX_SITE_ENABLED}" = "null" ] ; then
            NGINX_SITE_ENABLED=default
        fi

            if [ -n "${NGINX_SITE_ENABLED}" ] && [ "${NGINX_SITE_ENABLED,,}" != "null" ] ; then
                sites_to_enable=""
                for site_list in $(echo "${NGINX_SITE_ENABLED}" | tr "," "\n"); do
                    case "${site_list}" in
                        "all")
                            site_filelist=$(find "${NGINX_CONFIG_PATH%/}"/sites.available/*.conf /container/data/nginx/sites.available/*.conf /override/sites.available/*.conf -type f ! -name *.enc* -maxdepth 1 2>/dev/null || true)
                            for site_path in ${site_filelist}; do
                                sites_to_enable="${sites_to_enable} $(basename "${site_path%.*}")"
                            done
                        ;;
                        *)
                            sites_to_enable="${sites_to_enable} ${site_list}"
                        ;;
                    esac
                done

                # Deduplicate sites and count
                sites_to_enable=$(echo "${sites_to_enable}" | tr ' ' '\n' | sed '/^$/d' | awk '!seen[$0]++' | tr '\n' ' ')
                site_count=$(echo "${sites_to_enable}" | tr ' ' '\n' | sed '/^$/d' | wc -l | tr -d ' ')

                for site in ${sites_to_enable}; do
                    print_info "[configure_site/${site}] Enabling site"
                    call nginx_site_enable "${site}" "${site_count}"
                done
            fi
    else
        print_notice "[application_configuration] Disabled automated site configuration routines"
    fi
    call nginx_post_init
fi

liftoff
