#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2025 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
prepare_service defaults 10-nginx
SERVICE_NAME="nginx-config-reload"

prepare_service single
check_container_initialized
check_service_initialized init
liftoff

call nginx_config_reload_run
